### ISSUE TITLE
NBA Hang Time (USA).png

### ISSUE THREAD

**Issue by Europia79** [libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis#11]
![nba hang time usa](https://user-images.githubusercontent.com/4515713/51943656-abe37300-23df-11e9-921e-fe6d9177f065.png)

**Comment by Europia79** [comment]
The European resolution is 483x680.
The current USA rez is 256x362.
This new one is 353x500.

**Comment by RobLoach** [comment]
Feel free to submit Pull Requests for these! Then it'll be brought in easily. Thanks a lot.
